network: 'mainnet'
metaChainShardId: 4294967295
api:
  public: true
  private: true
  graphql: true
features:
  dataApi:
    enabled: false
    serviceUrl: 'https://data-api.multiversx.com'
  auth:
    enabled: false
    maxExpirySeconds: 86400
    acceptedOrigins:
      - ''
cron:
  transactionProcessor: false
  transactionProcessorMaxLookBehind: 1000
  cacheWarmer: false
flags:
  useRequestCaching: true
  useKeepAliveAgent: true
  useTracing: false
  collectionPropertiesFromGateway: false
urls:
  self: 'https://api.multiversx.com'
  elastic:
    - 'https://index.multiversx.com'
  gateway:
    - 'https://gateway.multiversx.com'
  verifier: 'https://play-api.multiversx.com'
  redis: '127.0.0.1'
  rabbitmq: 'amqp://127.0.0.1:5672'
  providers: 'https://internal-delegation-api.multiversx.com/providers'
  delegation: 'https://delegation-api.multiversx.com'
  media: 'https://media.elrond.com'
  maiarId: 'https://id-api.multiversx.com'
database:
  enabled: false
  url: 'mongodb://127.0.0.1:27017/api?authSource=admin'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  database: 'api'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  metabonding: 'erd1qqqqqqqqqqqqqpgq50dge6rrpcra4tp9hl57jl0893a4r2r72jpsk39rjj'
inflation:
  - 1952123
  - 1746637
  - 1541150
  - 1335663
  - 1130177
  - 924690
  - 719203
security:
  admins:
  jwtSecret:
test:
  mockKeybases: true
  mockNodes: true
  mockTokens: true
  mockPath: './src/test/mocks/'
transaction-action:
  mex:
    microServiceUrl: 'https://graph.xexchange.com/graphql'
