import axios from "axios";
import { config } from "./config/env.config";
import { fundAddress, transferEgld } from "./utils/chain.simulator.operations";
import { io, Socket } from "socket.io-client";
import { ChainSimulatorUtils } from "./utils/test.utils";

const WS_SERVER_URL = `${config.subscriptionsServiceUrl}`;

const txResponses: Map<string, any[]> = new Map();
const eventResponses: Map<string, any[]> = new Map();

const txFilters = {
  CLIENT_1: { sender: config.aliceAddress },
  CLIENT_2: { sender: config.bobAddress },
  CLIENT_3: { sender: config.aliceAddress, receiver: config.bobAddress },
};

const eventFilters = {
  CLIENT_1: { identifier: 'pong' },
  CLIENT_2: { address: '' }, // added dinamically after deploy sc
  CLIENT_3: { identifier: 'completedTxEvent', address: '' }, // added dinamically after deploy sc
};

const filterKeys = {
  CLIENT_1: "KEY_CLIENT_1",
  CLIENT_2: "KEY_CLIENT_2",
  CLIENT_3: "KEY_CLIENT_3",
};

const filterMap = [
  { key: filterKeys.CLIENT_1, txFilter: txFilters.CLIENT_1, eventFilter: eventFilters.CLIENT_1, clientId: "client1" },
  { key: filterKeys.CLIENT_2, txFilter: txFilters.CLIENT_2, eventFilter: eventFilters.CLIENT_2, clientId: "client2" },
  { key: filterKeys.CLIENT_3, txFilter: txFilters.CLIENT_3, eventFilter: eventFilters.CLIENT_3, clientId: "client3" },
];

let pingPongScAddress = '';

describe('Websocket subscriptions e2e tests (Txs and Events)', () => {
  const clients: Socket[] = [];

  const connectAndSubscribe = (filterKey: string, txFilter: any, eventFilter: any, clientId: string) => {
    const receivedTxs: any[] = [];
    const receivedEvents: any[] = [];

    txResponses.set(filterKey, receivedTxs);
    eventResponses.set(filterKey, receivedEvents);

    const client: Socket = io(WS_SERVER_URL, {
      path: '/ws/subscription',
    });
    clients.push(client);

    client.on("connect_error", (err) => {
      throw new Error(`${clientId} connection failed: ${err.message}`);
    });

    client.on("customTransactionUpdate", (data: { transactions: any[] }) => {
      console.log(`\n💸 ${clientId} received ${data.transactions.length} txs`);
      receivedTxs.push(...data.transactions);
    });

    client.on("customEventUpdate", (data: { events: any[] }) => {
      console.log(`\n🔔 ${clientId} received ${data.events.length} events`);
      receivedEvents.push(...data.events);
    });

    client.on("connect", () => {
      console.log(`\n   ${clientId} connected.`);

      client.emit("subscribeCustomTransactions", txFilter, (ack: any) => {
        console.log(`   ACK TXs ${clientId}:`, ack);
      });

      client.emit("subscribeCustomEvents", eventFilter, (ack: any) => {
        console.log(`   ACK Events ${clientId}:`, ack);
      });
    });
  };

  beforeAll(async () => {
    try {
      await fundAddress(config.chainSimulatorUrl, config.aliceAddress);
      await fundAddress(config.chainSimulatorUrl, config.bobAddress);
      await axios.post(`${config.chainSimulatorUrl}/simulator/generate-blocks/1`);

      pingPongScAddress = await ChainSimulatorUtils.deployPingPongSc(config.bobAddress);
      eventFilters.CLIENT_2.address = pingPongScAddress;
      eventFilters.CLIENT_3.address = pingPongScAddress;

      for (const item of filterMap) {
        connectAndSubscribe(item.key, item.txFilter, item.eventFilter, item.clientId);
      }

      await new Promise(resolve => setTimeout(resolve, 5000));

      console.log("\n--- Starting Operations ---");

      await transferEgld(config.chainSimulatorUrl, config.aliceAddress, config.bobAddress, 1);
      await transferEgld(config.chainSimulatorUrl, config.bobAddress, config.aliceAddress, 2);


      await ChainSimulatorUtils.pingContract(config.aliceAddress, pingPongScAddress);
      await ChainSimulatorUtils.pongContract(config.aliceAddress, pingPongScAddress);

      await axios.post(`${config.chainSimulatorUrl}/simulator/generate-blocks/10`);

      await new Promise(resolve => setTimeout(resolve, 15000));

    } catch (e: any) {
      console.error("Error in beforeAll:", e.message);
      throw e;
    }
  });

  afterAll(() => {
    clients.forEach(client => client.connected && client.disconnect());
  });

  it('should receive TXs sent by Alice for Client 1', () => {
    const txs = txResponses.get(filterKeys.CLIENT_1);
    expect(txs?.length).toBe(3);

    txs?.forEach((tx) => {
      expect(tx.sender).toEqual(config.aliceAddress);
    });
  });

  it('should receive Events with identifier "pong" for Client 1', () => {
    const events = eventResponses.get(filterKeys.CLIENT_1);
    expect(events?.length).toBe(1);

    events?.forEach((evt) => {
      expect(evt.identifier).toEqual('pong');
    });
  });

  it('should receive TXs sent by Bob for Client 2', () => {
    const txs = txResponses.get(filterKeys.CLIENT_2);
    expect(txs?.length).toBe(2);

    txs?.forEach((tx) => {
      expect(tx.sender).toEqual(config.bobAddress);
    });
  });

  it('should receive Events generated by PingPong contract (address) for Client 2', () => {
    const events = eventResponses.get(filterKeys.CLIENT_2);
    expect(events?.length).toBe(7);

    events?.forEach((evt) => {
      expect(evt.address).toEqual(pingPongScAddress);
    });
  });

  it('should receive specific Alice-to-Bob TXs for Client 3', () => {
    const txs = txResponses.get(filterKeys.CLIENT_3);
    expect(txs?.length).toBeGreaterThanOrEqual(1);

    txs?.forEach((tx) => {
      expect(tx.sender).toEqual(config.aliceAddress);
      expect(tx.receiver).toEqual(config.bobAddress);
    });
  });

  it('should receive Events with identifier "completedTxEvent" and from Ping Pong sc address for Client 3', () => {
    const events = eventResponses.get(filterKeys.CLIENT_3);
    expect(events?.length).toBe(2);

    events?.forEach((evt) => {
      expect(evt.identifier).toEqual('completedTxEvent');
    });
  });
});