name: Code Review

permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: tanghel/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
          MODEL:
          top_p: 1
          temperature: 1