name: Common Actions

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  warm:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: api
        ports:
          - 3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
      rabbitmq:
        image: rabbitmq:3-alpine
        ports:
          - 5672:5672
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS api;' -uroot -proot
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Initialize
        run: npm run init
      - name: Warm
        run: |
          if ${{ github.ref == 'refs/heads/main' }}; then
            npm run test:e2e:warm
          else
            npm run test:e2e:warm:mocked
          fi
        shell: bash
    outputs:
      redis: ${{ job.services.redis }}
      mysql: ${{ job.services.mysql }}
      rabbitmq: ${{ job.services.rabbitmq }}
