name: Integration Graph

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      mysql: ${{ needs.common.outputs.mysql }}
      rabbitmq: ${{ needs.common.outputs.rabbitmq }}
      redis: ${{ needs.common.outputs.redis }}

    needs: common

    steps:
      - name: Run integration tests
        run: npm run test:graph
